from collections.abc import AsyncIterator
from typing import Protocol


class StorageBackend(Protocol):
    async def put(self, data: bytes, *, content_type: str | None = None,
                  large: bool = False) -> str: ...
    async def get(self, ref: str) -> bytes: ...
    def open(self, ref: str) -> AsyncIterator[bytes]: ...
    async def delete(self, ref: str) -> None: ...
    async def exists(self, ref: str) -> bool: ...
